### PR TITLE
pin go-openapi/{analysis,spec,validate} versions

### PR DESCRIPTION
**Pull request by ags799**
Was using go-swagger 0.13.0 as a library until I noticed a compilation error between go-swagger and go-openapi/spec. I fixed it by specifying a commit for the go-openapi/spec dependency.

This commit is supposed to be for the 0.13.0 tag (commit b015bd). I couldn't open a PR unless I made the commit against master (I'm not that experienced with GitHub).

If this isn't merged, the workaround is for my client project to have
```toml
[[override]]
  name = "github.com/go-openapi/spec"
  revision = "a4fa9574c7aa73b2fc54e251eb9524d0482bb592"
```
in addition to its
```toml
[[constraint]]
  name = "github.com/go-swagger/go-swagger"
  version = "0.13.0"
```
in its `Gopkg.toml`. I'd much rather not need that `[[override]]` block (I'd much rather merge this PR).

### CODE REVIEW

**Comment by ags799** [comment]
Just want to be clear, I understand there are conflicts here. I'd like to create a `0.13.1` branch from the `0.13.0` tag, merge this PR into that new branch, and then release a new `0.13.1`.

But perhaps you all have other ideas.

**Comment by casualjim** [comment]
How come you are depending on go-swagger/go-swagger ?

**Comment by ags799** [comment]
@casualjim I'm working with APIs defined in [JSON Hyper Schema](http://json-schema.org/). Wish I was using Swagger 😢.

I'd still like to use go-swagger's code generation. So I've wrapped go-swagger with another program that converts JSON Hyper Schema into Swagger, then uses go-swagger to generate code from that.

Also, it looks like I need to specify revisions for the other go-openapi projects used by Swagger. More commits on the way.

**Comment by JonKohler** [comment]
Where are we with this PR? This seems like a good idea overall.

**Comment by ags799** [comment]
I think it needs an approving review? I don't use go-swagger anymore so idc.

**Comment by fredbi** [comment]
I think it would be wiser to tag the goopenapi repos as releases

**Pull request closed without merging**
