### PR TITLE
use different bindata binary

### PR DESCRIPTION
**Pull request by casualjim**
updates to build with go 1.11
fixes a number of shellcheck issues

### CODE REVIEW

**Comment by fredbi** [comment]
this new --vet off option... does it mean that our generated stuff does not pass vet with go 11?

**Comment by fredbi** [comment]
Can't merge PRs any longer.

**Comment by casualjim** [comment]
That is correct because of the debugLog and debugLogAsJSON methods, the format strings are of wrong type and/or missing a format param.

**Comment by fredbi** [comment]
We have the same kind of construct in generated code -see issue #1573.
IMHO go vet just got overboard with 1.10

**Pull request merged**
