### PR TITLE
scan: treat error primitive as string

### PR DESCRIPTION
**Pull request by fsouza**
Related to #241.

### CODE REVIEW

**Comment by casualjim** [comment]
lgtm

**Comment by fsouza** [comment]
@casualjim thanks for merging!

**Comment by casualjim** [comment]
thank you for using and improving the tool, sir!

**Comment by supereagle** [comment]
The commit ea284b6 causes the example "fixtures/goparsing/petstore" can not generate the swagger spec.

Under the folder "fixtures/goparsing/petstore/petstore-fixture", run the command: swagger.exe  generate spec -o ./swagger.json. It reports the error: unknown primitive "error".

After I reverted the commit ea284b6, the generate spec command can correctly work.

@fsouza  I'm a fresher on go-swagger. Could you help to have a look at this problem? Thanks.

**Comment by fsouza** [comment]
Hi @supereagle, that's because you haven't recompiled swagger.exe. Please try running ``go get -u github.com/go-swagger/go-swagger/cmd/swagger``.

**Comment by supereagle** [comment]
@fsouza  Thanks for your help.

**Pull request merged**
