### PR TITLE
generator: strip package name from type name

### PR DESCRIPTION
**Pull request by rjeczalik**
Quick fix for #844.

### CODE REVIEW

**Comment by casualjim** [comment]
can you run `go generate ./generator` so that the template changes are included in the binary?

**Comment by rjeczalik** [comment]
@casualjim Done.

What about adding actual stale file check to your ci? It'd be something like:

```diff
$ git diff HEAD~1
diff --git a/appveyor.yml b/appveyor.yml
index c072bad..6a03635 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -44,6 +44,10 @@ install:
   - go get -u gopkg.in/matm/v1/gocov-html
   - go get -u github.com/cee-dub/go-junit-report
 
+  # check for stale files
+  - go generate -v ./generator
+  - git diff --exit-code ./generator
+
 build_script:
   - cd %APPVEYOR_BUILD_FOLDER%
   - echo %PATH%
diff --git a/generator/shared.go b/generator/shared.go
index 81df7c3..38564ef 100644
--- a/generator/shared.go
+++ b/generator/shared.go
@@ -34,7 +34,7 @@ import (
        "golang.org/x/tools/imports"
 )
 
-//go:generate go-bindata -pkg=generator -ignore=.*\.sw? ./templates/...
+//go:generate go-bindata -mode 420 -modtime 1482416923 -pkg=generator -ignore=.*\.sw? ./templates/...
 
 // LanguageOpts to describe a language to the code generator
 type LanguageOpts struct {
```

**Comment by casualjim** [comment]
sure if you want to add by all means :)

**Comment by rjeczalik** [comment]
@casualjim Please don't merge yet, testing if the check works.

**Comment by rjeczalik** [comment]
@casualjim Ok, looks like .git directory is removed from go-swagger before install stage:

```
git diff --exit-code ./generator
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Command exited with code 129
```

It'd require more work, for a separate PR - let's merge the fix first.

**Comment by rjeczalik** [comment]
Previous fix was wrong, I've stripped package from wrong variable - it should be GoType instead.

How to best add a test for building fixtures/codegen/issue844.json?

**Comment by GlenDC** [comment]
@rjeczalik you can do so by adding a (unit) Test function named `TestIssue844` in https://github.com/go-swagger/go-swagger/blob/master/generator/model_test.go. There you can load the spec file, which it should be able to load without any errors. After that you could, if applicable, also test specifics. In the `model_test.go` file you'll see other examples that could give you inspiration if needed.

**Comment by GlenDC** [comment]
Once you added the unit test @rjeczalik, you'll have to also fetch & rebase the latest master branch into your personal feature branch. You can resolve the conflict of `generator/bindata.go`, simply by generating a new one yourself, which contains both the latest templates (which you've just fetched & rebased) and your changes already committed in this PR.

Once that's done this PR is good to go :)

**Comment by rjeczalik** [comment]
I've added a test that generates a client and then tries to build it. The test currently fails due to a different problem:

```
--- FAIL: TestGenerateAndBuild (0.28s)
    --- FAIL: TestGenerateAndBuild/issue_844 (0.28s)
        build_test.go:40: go get ../fixtures/bugs/844/generated398758314/...: exit status 2
                # github.com/go-swagger/go-swagger/fixtures/bugs/844/generated398758314/client/operations
                ../fixtures/bugs/844/generated398758314/client/operations/get_responses.go:117: o.Foo.Validate undefined (type models.Foo is interface with no methods)
                ../fixtures/bugs/844/generated398758314/client/operations/get_responses.go:121: o.Bar.Validate undefined (type models.Bar is interface with no methods)
```

Indeed the generated models lack a Validate method. Not quite sure it's a regression, as every other test passes:

```
$ go test -run -TestGenerateAndBuild
PASS
ok      github.com/go-swagger/go-swagger/generator      0.197s
```

Probably we'd want to have this problem also fixed before merging, so we do not have a broken master.

**Comment by rjeczalik** [comment]
I've added a test that generates a client and then tries to build it. The test currently fails due to a different problem:

```
--- FAIL: TestGenerateAndBuild (0.28s)
    --- FAIL: TestGenerateAndBuild/issue_844 (0.28s)
        build_test.go:40: go get ../fixtures/bugs/844/generated398758314/...: exit status 2
                # github.com/go-swagger/go-swagger/fixtures/bugs/844/generated398758314/client/operations
                ../fixtures/bugs/844/generated398758314/client/operations/get_responses.go:117: o.Foo.Validate undefined (type models.Foo is interface with no methods)
                ../fixtures/bugs/844/generated398758314/client/operations/get_responses.go:121: o.Bar.Validate undefined (type models.Bar is interface with no methods)
```

Indeed the generated models lack a Validate method. Not quite sure it's a regression, as every other test passes:

```
$ go test -run -TestGenerateAndBuild
PASS
ok      github.com/go-swagger/go-swagger/generator      0.197s
```

Probably we'd want to have this problem also fixed before merging, so we do not have a broken master.

**Comment by GlenDC** [comment]
@rjeczalik I think your test file triggered a bug in the current generator code already on master.

The template responsible for your non-compiable code can be found here: https://github.com/go-swagger/go-swagger/blob/master/generator/templates/schemavalidator.gotmpl#L251

The appropriate fix would probably be to ensure that we don't try to validate in case it's an interface. So within that range you're probably missing an if/conditional check to ensure it's indeed not an interface or I suppose it's called discriminator in Swagger/OpenAPI terms.

Would be cool if you could fix this alongside your other commits within this PR.

Also don't forget to rebase origin/master into your branch.

**Comment by rjeczalik** [comment]
> Also don't forget to rebase origin/master into your branch.

Already rebased.

> Would be cool if you could fix this alongside your other commits within this PR.

Sure, will take a look.

**Comment by rjeczalik** [comment]
@GlenDC Fixed, please take a look.

**Comment by GlenDC** [comment]
Thank you for the extra effort @rjeczalik, very much appreciated.

**Comment by rjeczalik** [comment]
@GlenDC You're welcome :-)

**Pull request merged**
