### PR TITLE
Fix missing error check on s.Shutdown()

### LINKED ISSUE #1689: errcheck failed on generated restapi/server.go#handleInterrupt
## Steps to reproduce
```bash
go get -u github.com/kisielk/errcheck
errcheck $(go list ./...) | grep Shutdown
# print:
# restapi/server.go:499:14:       s.Shutdown()
```

Example of failed build: https://travis-ci.org/c0va23/redirector/builds/426186512#L691

## Environment
swagger version: master 
go version: any
OS: any

Template line:
https://github.com/go-swagger/go-swagger/blob/b10bd7b2c916c12928f64efcfc1391c864b54480/generator/templates/server/server.gotmpl#L621

### PR DESCRIPTION
**Pull request by MrLuje**
fixes #1689

### CODE REVIEW

**Comment by casualjim** [comment]
This fails the build.

**Comment by fredbi** [comment]
The pushed bindata.go does not reflect the change in the template, but many others. Looks like the generation was not performed on a clean branch

**Comment by MrLuje** [comment]
All failing tests are related to line endings (I'm on windows)

Do you mind if I also add a .gitattributes file with the following code to avoid this issue next time ?

`*.gotmpl		text eol=lf`

**Comment by casualjim** [comment]
go ahead

**Pull request merged**
