### PR TITLE
ci: made codegen-nonreg.sh script less sensitive to merge conflicts

### PR DESCRIPTION
**Pull request by fredbi**
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

**Comment by fredbi** [comment]
This is just a technical change in the CI script to ease a bit merge issues when rebasing PR which add some new specs to the global codegen build test.

**Comment by casualjim** [comment]
There is a merge conflict here that I'm not sure how to resolve

**Comment by fredbi** [comment]
@casualjim  I'll merge this last.
Anyway, while doing this, I have been considering some larger CI undertaking: I'd wish to replace this ugly shell script by a golang test commander, which we could more easily parallelize. What do you think of https://godoc.org/gotest.tools/icmd ?

**Comment by casualjim** [comment]
fine by me

**Pull request merged**
