### PR TITLE
skip fields in parameter structs with struct tag `json:"-"`

### PR DESCRIPTION
**Pull request by jlburkhead**
Signed-off-by: Jake Burkhead <jake.b@socialcodeinc.com>

relates to https://github.com/go-swagger/go-swagger/issues/520

### CODE REVIEW

**Comment by casualjim** [comment]
lgtm

**Comment by rookie7799** [comment]
Howdy, 
Is it possible to skip a field with some special syntax under `swagger:parameters` and not just with `json:"-"` ? Eg:

```
// swagger:parameters listBars
type BarParam struct {
// skip: true
Field string `json:"field"`
...
```

**Comment by casualjim** [comment]
if you're sending it with the json doesn't it need to be included in your contract?

**Comment by rookie7799** [comment]
Right, but I'm using the same struct elsewhere that is not part of swagger
and it needs that 'json' tag.

**Comment by casualjim** [comment]
you could teach go-swagger to also recognize `swagger:` as struct tag perhaps as alternative? Should be fairly straightforward because it's the same as this PR

**Pull request merged**
