### PR TITLE
Fix #1274 - add a new template variable in GenCommon.

### LINKED ISSUE #1274: custom templating: need the target path as base import
## Problem statement
When customizing templates, or configuring new templates, I found difficult to retrieve the base import directory in the generated target.

This path is known to internal templates but not exposed to all templates

Proposed a PR to add a "TargetImportPath" in the common structure accessible to all templates (next to "Copyright").

This may be used as {{ .TargetImportPath }} in any template.

Example use-case:
- I added a new custom "implementation" package under the target path which should be imported by a customized configureapi.go
- with {{ .TargetImportPath }}, I can produce custom imports rebased to the target generation path, without tinkering with DefaultImports configuration of standard templates

## Swagger specification
N/A

## Steps to reproduce
N/A

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

### PR DESCRIPTION
**Pull request by fredbi**
Extended template unit testing to validate environments from standard templates (missing: codeGenApp context)

### CODE REVIEW

**Comment by fredbi** [comment]
I am lost with AppVeyor report.  There is no indication of what has gone wrong for this bot.
On my side, all tests are passing. 
Any hint?

**Comment by casualjim** [comment]
it fails because it's printing to stderr

**Comment by fredbi** [comment]
Well, ok. I am will to abide by these ever stricter rules (!).
Any indication as for where this occurs? This branch has changed much code, so I am lost.

**Comment by casualjim** [comment]
Windows (appveyor) thinks anything that prints to stderr is a failure

**Comment by fredbi** [comment]
I could see this AppVeyor CI deployed on windows.
I am just wondering if it's connected to my changes in this particular PR or it's just because you did set up AppVeyor just recently and swagger is croaking a lot on stderr ?

**Comment by casualjim** [comment]
I suspect it has to do with the new log statemetns that were added 

AppVeyor has been going for more than a year on this project

**Comment by fredbi** [comment]
No logging has been explicitely added in this branch.
However I think I get your point: since I call some high level methods in the new unit test, this probably croaks on stderr. I'll work on that hypothesis to get it right.

**Comment by fredbi** [comment]
@casualjim . Just to make sure I am not spending time in the wrong direction.
If I fix the CI issue you're okay with the feature?
[if not, no problem, I'll just keep it on my fork, since I do need it: just simpler for me to avoid branching]

**Comment by casualjim** [comment]
yes fine with the feature

**Comment by casualjim** [comment]
this might give you an idea how to avoid the stderr issue:
https://github.com/go-swagger/go-swagger/blob/master/generator/operation_test.go#L367-L370

**Comment by fredbi** [comment]
Thanks Ivan. This is exactly how I did it.
I had to fix precisely this other unit test which had a side effect by switching log back to Stderr after muting it.
Besides the Execute() method I test had an end message with fmt.Fprintf(Stderr,...). Had to fix that too.

Ok. So when I run the full test on generator pkg, stderr is empty. There must be a catch.

**Comment by fredbi** [comment]
I fixed the issue occuring on windows. Now waiting for master to be repaired to rebase my branch. 
Cheers

**Comment by casualjim** [comment]
master should be repaired now, sorry about that

**Pull request merged**
