### PR TITLE
Fixed panic in `AddMiddlewareFor` method if method is not uppercase

### PR DESCRIPTION
**Pull request by iv-menshenin**
Use the same variable to set the handler value by key

### CODE REVIEW

**Comment by iv-menshenin** [comment]
If you call a method and pass a non uppercase word as an argument to method, it will inevitably panics because we are not using the same (that we checked when getting) value as the key when setting the value.

**Review by casualjim — APPROVED** [review]

**Comment by iv-menshenin** [comment]
Why didn't it pass the lint? I don't see any details

**Comment by iv-menshenin** [comment]
@casualjim can you help me with linter? What does it want from me?

**Comment by casualjim** [comment]
Sorry I saw this failure and I fixed the build on master, not sure how that ever went through in the first place. 
I've just rebased your branch, we'll see how it does now

**Comment by iv-menshenin** [comment]
Forgot `signed-off`

**Comment by iv-menshenin** [comment]
Sorry, I forgot my `signed-off` in comment and then couldn't deal with your rebase in my branch =)
Please fix it yourself, or I can repeat my request  later

**Comment by casualjim** [comment]
the signed off I should remove that. the pr was good

**Comment by iv-menshenin** [comment]
> If you call a method and pass a non uppercase word as an argument to method, it will inevitably panics because we are not using the same (that we checked when getting) value as the key when setting the value.

re-created the request

https://github.com/go-swagger/go-swagger/pull/2928

**Pull request closed without merging**
