### PR TITLE
#2748 passing request context to ConextValidate()

### PR DESCRIPTION
**Pull request by dimovnike**
Signed-off-by: Nick Dimov <3619341+dimovnike@users.noreply.github.com>

### CODE REVIEW

**Comment by casualjim** [comment]
Looks like there is a test that actually asserts the line you changed

**Comment by dimovnike** [comment]
Submitted a fix. The problem  is that i can not run tests locally, they fail even in master:

```
--- FAIL: TestClient (35.47s)                                                                                                                                                                                                          
    --- FAIL: TestClient/generate_client (0.00s)                                                                                                                                                                                       
        --- FAIL: TestClient/generate_client/packages_mangling (4.87s)                                                                                                                                                                 
            utils_test.go:30:                                                                                                                                                                                                          
                        Error Trace:    utils_test.go:30                                                                                                                                                                               
                                                                client_test.go:133                                                                                                                                                     
                                                                client_test.go:234                                                                                                                                                     
                                                                client_test.go:309                                                                                                                                                     
                        Error:          Expect "// Code generated by go-swagger; DO NOT EDIT.                                                                                                                                          
                                                                                                                                                                                                                                       
                                        package client                                
...
```
hope this will work!

**Review by youyuanwu — APPROVED** [review]

**Comment by casualjim** [comment]
@dimovnike what are the errors you see when you build locally?  Can you share which OS + CPU architecture you are developing on?

**Comment by dimovnike** [comment]
> @dimovnike what are the errors you see when you build locally? Can you share which OS + CPU architecture you are developing on?

the build is ok but go test is failing.  I use Ubuntu 20.04, and go version go1.16.7 linux/amd64.

I just found this in the error log:

> note: module requires Go 1.17 

its probably because of this. I will update golang and will try again.

**Pull request merged**
