### PR TITLE
fix typo in server/builder.gotmpl

### LINKED ISSUE #853: Mistype
[go-swagger/generator/templates/server/builder.gotmpl:82](https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/builder.gotmpl#L82)
"functin" instead of "function"

### PR DESCRIPTION
**Pull request by GlenDC**
fixes #853 

Replaces original PR #854

### CODE REVIEW

**Comment by vburenin** [comment]
@GlenDC generator/bindata.go is always a pain to merge if template is changed.

**Comment by GlenDC** [comment]
@vburenin Yes, I'll just push to the branch a newly generated bindata, with the latest master merged into it, that's usually how I resolve it.

@casualjim is by the way sick AFAIK, so he might not be around for a while.

**Comment by GlenDC** [comment]
@vburenin rebased master on it, and forced push the originally commit again. This branch should now have the latest changes of master in it. So hopefully there are no merge conflicts any longer. So if all tests pass, I think you are free to merge in this PR, in case you still approve.

**Comment by vburenin** [comment]
@GlenDC yah, @casualjim is sick, hopefully he get well soon.

**Pull request merged**
