### PR TITLE
Add support for --strict-additional-properties

### PR DESCRIPTION
**Pull request by connesc**
Implements what have been proposed in #2035.

When `--struct-additional-properties` is set, models with `additionalProperties: false` (which is the default) are given a custom `UnmarshalJSON` with [`Decoder.DisallowUnknownFields`](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields) enabled.

### CODE REVIEW

**Comment by casualjim** [comment]
To get this functionality you can also just register a different jsonconsumer with those settings. Might be easier: https://github.com/go-openapi/runtime/blob/master/json.go

You then register that for the mimetype and you get the behavior without any changes to the generated code

**Comment by fredbi** [comment]
Looks good to me.

**Comment by connesc** [comment]
Thanks for the advise @casualjim, it seems to work perfectly as well!

So, now there are two interesting options for the same goal, with subtle differences:
- Registering a custom `runtime.Consumer` does not have any performance overhead.
- Generating a custom `json.Unmarshaler` enforces the Swagger spec directly in the generated code.

Also, I'm not sure how both options interact with other generated custom unmarshalers (e.g. for `allOf` or polymorphic types).

@casualjim @fredbi I let you decide whether this should be merged or not. I will just rebase the PR and regenerate `bindata.go` to fix conflicts.

**Comment by fredbi** [comment]
@connesc nice analysis and work. Indeed we have two solution to handle strict validation.

The runtime approach is more elegant when running the full fledged toolkit. I like just as much the model-only approach as it is opt-in and allows for stricter jsonschema compliance when dealing with generated models only.

**Comment by casualjim** [comment]
I kind of want to revert this. Because it seems like an ad-hoc addition that duplicates functionality that already exists in a verbose way. At the same time the interplay with additional properties, additional items and tuples is not clear. it's also not clear how it behaves with discriminated types.

**Comment by fredbi** [comment]
@casualjim additionalItems is not affected (the template name is misleading, and this has been so for quite a long time).

There might indeed be some limitations with this simple addons regarding complex structures (allOf, etc), but overall I think it is a good addition.

I think of the models feature as kind of standalone and not necessarily coupled with the use of the go-openapi runtime, so I am not seeing this as duplicate functionality. I would not revert this, but to the contrary, maybe someday extend it to support additionalItems etc.

**Pull request merged**
