### PR TITLE
intentionally bad change for golangci

### PR DESCRIPTION
**Pull request by JonKohler**
intentionally bad change for golangci

This should be flagged up and down by golangci, let's see what happens

### CODE REVIEW

**Comment by JonKohler** [comment]
welp, thats embarassing. let's try that again

**Comment by JonKohler** [comment]
I need to reopen another junky PR to get it run again

**Comment by fredbi** [comment]
Does the golangCI checks just for changes or run against the whole existing code?
I am running gometalinter from time to time, and we have a lot of warning to fix.

**Comment by JonKohler** [comment]
It JUST checks the changes, as that would make PR's a nightmare for projects that

I did use gometalinter for a while, until I found golangci's CLI, and I really, really like it instead.

**Comment by JonKohler** [comment]
Give this a try and see how you like it: https://github.com/golangci/golangci-lint

**Comment by fredbi** [comment]
Yeah I looked at this link this morning to figure out changes re gometalinter.
What would be interesting is to run this in CI on sample generated code as well.

**Pull request closed without merging**
