### PR TITLE
Proposed solution to Issue #198

### PR DESCRIPTION
**Pull request by Tobi042**
Added a shutdown hook in main. It can be assigned to the newly created variable in the xxxAPI struct during configuration. The parameter is preinitialized for backwards compatibility comaptibility reasons.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/go-swagger/go-swagger/pull/199%23issuecomment-170052260%22%2C%20%22https%3A//github.com/go-swagger/go-swagger/pull/199%23issuecomment-170067151%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/199%23issuecomment-170052260%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Forgot%20signed-off-by%20message%22%2C%20%22created_at%22%3A%20%222016-01-08T16%3A47%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1289180%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobi042%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-08T17%3A33%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/casualjim%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/casualjim%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/casualjim'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/go-swagger/go-swagger/pull/199#issuecomment-170052260'>General Comment</a></b>
- <a href='https://github.com/Tobi042'></a> Forgot signed-off-by message

<a href='https://www.codereviewhub.com/go-swagger/go-swagger/pull/199?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/go-swagger/go-swagger/pull/199?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/go-swagger/go-swagger/pull/199?approve=0'></a>&nbsp;<a href='https://github.com/go-swagger/go-swagger/pull/199'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by casualjim** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/go-swagger/go-swagger/pull/199'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobi042** [comment]
Forgot signed-off-by message

**Comment by casualjim** [comment]
:shipit:

**Comment by casualjim** [comment]
thanks for this, cleaner solution I had in mind.

**Comment by Ravenwater** [comment]
I see the api.ServerShutdown method hook in the generated struct, but how is it invoked/what invokes this method?

**Comment by casualjim** [comment]
when you send a signal (SIGINT, SIGQUIT) to shut it down to your program. It functions as a finalizer when for example ctrl-c is pressed. It's where you cleanly release file handles etc

**Comment by casualjim** [comment]
you're on windows right? There is a config key for it:
https://youtrack.jetbrains.com/issue/PY-17252

**Comment by Ravenwater** [comment]
Pending investigation how to configure the "Stop Process" button in the IntelliJ IDE. According to customer support it is only supported for the JVM, and would need to be added by the Golang plugin for Golang processes.

**Pull request merged**
