### PR TITLE
Fix graceful-timeout variable

### PR DESCRIPTION
**Pull request by gregorhollmig**
During enhancing go-swagger generator as mentioned in issue #1714, as an accident in #1730 the command line parameter `--graceful-timeout=50s` was interpreted as float and for `WithTimeout` multiplied by `*time.Second`

The code doesn't fail but `context deadline exceeded` will be immediately executed.

This fixes the issue.

### CODE REVIEW

**Comment by fredbi** [comment]
Hello. How come you can update a template and commit without regenerating bindata.go ?

**Comment by fredbi** [comment]
Yes it should. There is a script .githools/pre-commit/50xxx for that

**Comment by fredbi** [comment]
Ah, again the commit signing involved... Best to rebase and sign in one pass (_every commit_ is required to be signed...)

**Comment by gregorhollmig** [comment]
Is further action required by my side for the PR to be merged? 
The signing is sth. I haven't done before, I need to get used to that...

**Comment by fredbi** [comment]
this checks _all_ your commits...

**Comment by casualjim** [comment]
one is sign-off the other is sign with pgp key.
You're missing the sign with pgp key. Just the last commit will be fine.

**Comment by casualjim** [comment]
https://help.github.com/articles/about-commit-signature-verification/

**Comment by casualjim** [comment]
git hooks don't get installed automatically you have to enable them manually first and then it should start to work.

**Comment by gregorhollmig** [comment]
Okay @casualjim  so ... I signed with `commit -s` isn't that fine? I believe I did the same for #1730 . DCO check is also fine, what is the issue?

**Comment by fredbi** [comment]
@gregorhollmig  -s only add your email to the commit text.  I think the new CI check also verifies that your commit is _cryptographically_ signed with a PGP signature. You can check this for example, when doing `git log --show-signature`. This means configuring PGP keys, and configuring git to use these keys to PGP-sign your commits.

**Comment by gregmarr** [comment]
@casualjim there is no mention in CONTRIBUTING.md that PGP signature is required.  Is this an intentional change?  If so, it should be added there.

**Comment by fredbi** [comment]
Yep, this came a bit unannounced... This could also be detailed here: https://github.com/go-swagger/go-swagger/tree/master/docs/guidelines

**Comment by casualjim** [comment]
This PR is not the right place to have this discussion

**Pull request merged**
