### PR TITLE
Move to context from x/net/context in generated code

### PR DESCRIPTION
**Pull request by mstoykov**
I am not sure I regenerated everything correctly see #1720 

The examples were regenerated but their imports were wrong : 
```diff
diff --git a/examples/authentication/cmd/auth-sample-server/main.go b/examples/authentication/cmd/auth-sample-server/main.go
index 7150b413..47537a72 100644
--- a/examples/authentication/cmd/auth-sample-server/main.go
+++ b/examples/authentication/cmd/auth-sample-server/main.go
@@ -7,8 +7,8 @@ import (
        "os"

        loads "github.com/go-openapi/loads"
-       "github.com/go-swagger/go-swagger/examples/authentication/restapi"
-       "github.com/go-swagger/go-swagger/examples/authentication/restapi/operations"
+       "github.com/go-swagger/restapi"
+       "github.com/go-swagger/restapi/operations"
        flags "github.com/jessevdk/go-flags"
 )
```

I couldn't figure out why so I just didn't commit them :)

### CODE REVIEW

**Comment by fredbi** [comment]
did you use the sample regen script? AFAIK there is a small test that at least all examples build.

**Comment by fredbi** [comment]
I am using this go-bindata: github.com/jteeuwen/go-bindata

**Comment by casualjim** [comment]
I just tried these changes locally.
I installed the same go-bindata you're using and I ran the ./hack/regen-samples.sh script

The changes it makes seem all to be expected

**Comment by fredbi** [comment]
@MStoykov you just need to rebase and regenerate. I've pushed a PR that does just that on your own fork.

**Pull request closed without merging**
