### PR TITLE
Allow parameter code generation when struct is inside a function.

### PR DESCRIPTION
**Pull request by josephspurrier**
Also removes the extra log left in the repo. Closes https://github.com/go-swagger/go-swagger/issues/1545.

### CODE REVIEW

**Comment by josephspurrier** [comment]
I'll add some tests so the code coverage doesn't go down. I'm going to add in similar code for the responses as well.

**Comment by casualjim** [comment]
excellent! I'll wait with merging then?

**Comment by josephspurrier** [comment]
Yeah, give me a couple days and I'll update the pull request. Thanks!

**Comment by josephspurrier** [comment]
It should be good to go. Let me know if I need to make any changes.

**Pull request merged**
