### PR TITLE
#2199 Remove the duplicate `withEnum` functions inside `scan` package

### LINKED ISSUE #2199: Build fails due to duplicate methods
src/github.com/go-swagger/go-swagger/scan/parameters.go:75:6: paramTypable.WithEnum redeclared in this block
	previous declaration at src/github.com/go-swagger/go-swagger/scan/parameters.go:43:6
src/github.com/go-swagger/go-swagger/scan/parameters.go:110:6: itemsTypable.WithEnum redeclared in this block
	previous declaration at src/github.com/go-swagger/go-swagger/scan/parameters.go:94:6
src/github.com/go-swagger/go-swagger/scan/responses.go:97:6: responseTypable.WithEnum redeclared in this block
	previous declaration at src/github.com/go-swagger/go-swagger/scan/responses.go:41:6
src/github.com/go-swagger/go-swagger/scan/scanner.go:477:2: duplicate method WithEnum
src/github.com/go-swagger/go-swagger/scan/schema.go:1047:8: ambiguous selector prop.WithEnum
The command '/bin/sh -c go get github.com/go-swagger/go-swagger/cmd/swagger' returned a non-zero code: 2
The command "docker build -f Dockerfile -t $DOCKER_IMAGE_NAME:$COMMIT ." failed and exited with 2 during .

TravisCLI
go version: 1.10.3  
OS: linux/amd64

### PR DESCRIPTION
**Pull request by sam016**
Fixes  #2199

### CODE REVIEW

**Comment by naga-beeram** [comment]
Can someone merge this please!

**Comment by sam016** [comment]
This is one more active issue. Fixing it.

```
type swaggerTypable interface {
	Typed(string, string)
	SetRef(spec.Ref)
	Items() swaggerTypable
	WithEnum(...interface{})
	Schema() *spec.Schema
	Level() int
	WithEnum(...interface{})
}
```
multiple `	WithEnum(...interface{})`

Just got the docker go1.10 to verify the build.

**Comment by sam016** [comment]
Fixed and verified the build in Go 1.10

**Comment by naga-beeram** [comment]
Can someone merge this please!

**Pull request merged**
