### PR TITLE
Fix 1040: make generation of api key authencator customizable.

### PR DESCRIPTION
**Pull request by dreamlover**
Signed-off-by: lfree xh <xh.dreamlover@gmail.com>

### CODE REVIEW

**Comment by casualjim** [comment]
Thanks, would it be possible to do the same for BasicAuth and BearerAuth so that it's a consistent pattern?

**Comment by dreamlover** [comment]
OK, BasicAuth and BearerAuth added.

**Comment by casualjim** [comment]
The build is failing because of name collisions, those authenticators should either figure out unique names, but I think a reasonable work around is to call the properties: ApiKeyAuthenticator, BasicAuthenticator and BearerAuthenticator

**Comment by casualjim** [comment]
thanks!

**Pull request merged**
