### PR TITLE
Use spec BasePath when it is non-empty.

### PR DESCRIPTION
**Pull request by nikhilm**
This fixes the issue, but I'd like to know a good place to put a test for this (or modify an existing test).
In addition, I'm opening the PR so I know the existing test-suite passes because
1) I couldn't find instructions on how to run all tests locally
2) The Circle process I ran on my fork failed - https://circleci.com/gh/nikhilm/go-swagger/3

### CODE REVIEW

**Comment by casualjim** [comment]
I run tests locally like this:

```
go test $(go list ./... | grep -v vendor)
```

Another way to do it is:

```
docker build -t go-swagger:local -f Dockerfile.ci .
docker run --rm -it go-swagger:local ./hack/build-docker.sh
```

And the last way to do it is:

```
drone exec
```

**Comment by nikhilm** [comment]
existing test suite passed locally, where should I put the new test and
what can I use as an example for this kind of test? Thanks!

On Tue, Apr 5, 2016 at 4:46 PM, Ivan Porto Carrero <notifications@github.com

**Comment by casualjim** [comment]
I think writing a test for this would only matter for the client generation stuff. The BasePath property is used in the client facade


it looks a bit like these tests: https://github.com/go-swagger/go-swagger/blob/master/generator/operation_test.go#L301-L375

the template for that is: `clientFacadeTemplate`
and you're checking if this bit renders correctly: `transport := httptransport.New({{ printf "%#v" .Host }}, {{ printf "%#v" .BasePath }}, {{ printf "%#v" .Schemes }})`

**Comment by nikhilm** [comment]
The CircleCI failures don't seem to be my fault.

**Comment by casualjim** [comment]
lgtm 

I go by the drone one, I should remove the circle one I won't be using it anymore going forward.

**Comment by casualjim** [comment]
Thanks a lot!

**Pull request merged**
