### PR TITLE
revert changes to CLI params

### PR DESCRIPTION
**Pull request by casualjim**

### CODE REVIEW

**Comment by nelz9999** [comment]
This was related to #587 and #612, right?

I was actually looking forward to those changes. Was there any further discussion about this?

**Comment by casualjim** [comment]
no further discussion yet, but the changes won't be lost. Their intent will be brought back but in a less breaking fashion.
Some signatures changed without there being a real reason for the change and the args also changed too much for their intended use.

So I think the intent is we don't want the spec to decide between https, http or unix sockets. We want that to be decision that is made when we start the process of the server. Would you agree that that is the change you want preserved?

**Comment by vburenin** [comment]
I want to be in the control where and how I listen to client connections as
well as what is in the spec shemes list independently.

**Comment by nelz9999** [comment]
> So I think the intent is we don't want the spec to decide between https, http or unix sockets. We want that to be decision that is made when we start the process of the server. Would you agree that that is the change you want preserved?

Yup, that is exactly what I was looking for!

**Pull request merged**
