### PR TITLE
Removed redundant code. Less JSON parsing. Speedups on many things in…

### PR DESCRIPTION
**Pull request by vburenin**
Removed redundant code. Less JSON parsing. Speedups on many things into several times. The larger spec is, the more noticeable speed up.

### CODE REVIEW

**Comment by casualjim** [comment]
lgtm

**Comment by bfirsh** [comment]
This broke my build:

```
$ go get github.com/go-swagger/go-swagger/cmd/swagger
# github.com/go-swagger/go-swagger/generator
generator/types.go:244: doc.OrigSpec undefined (type *loads.Document has no field or method OrigSpec)
```

**Comment by vburenin** [comment]
Did you update all dependencies? This thing is defined in github.com/go-openapi/loads, I guess that is why.

**Comment by bfirsh** [comment]
Yep - go-openapi/loads doesn't seem to have a OrigSpec field on Document.

**Comment by vburenin** [comment]
does it work now?

**Comment by casualjim** [comment]
We fixed this yesterday in the correct repo. you may have to do a `go get -u github.com/go-openapi/loads`

**Comment by bfirsh** [comment]
Ah, thanks!

**Pull request merged**
