### PR TITLE
Improve client response error message when status code not recognized

### PR DESCRIPTION
**Pull request by minitauros**
I was debugging a failing test and I saw this error message and thought "huh, did I not set up my mocks correctly? what's going on here?". It actually took me a while before checking the generated swagger code and realizing that all I did wrong is have my mock return the wrong response status code.

### CODE REVIEW

**Comment by casualjim** [comment]
can you run `go generate ./generator` otherwise the changes to the template won't get picked up

**Comment by minitauros** [comment]
My bad, must have missed some instructions.

Ran it and added it as a new commit.

**Comment by casualjim** [comment]
Github won't let me merge this because of merge conflicts in bindata.go, could you pull master first?

**Comment by minitauros** [comment]
Pulled master, rebased, force pushed.

Apologies for the force push since you can't see the diff. Not sure what kind of reviewing strategy you prefer.

**Comment by casualjim** [comment]
That's fine, we only care about the final changeset. Thanks!

**Pull request merged**
