### PR TITLE
enhancement: Add `.Pointer()` method to enums.

### PR DESCRIPTION
**Pull request by thetorpedodog**
Following the example of protobuf generated code, this change creates
a `.Pointer()` method on enums that creates a new, non-aliased pointer
to an enum value.

This means that you can call:

    enumPtr := SomeEnumConst.Pointer()

to get a pointer to an enum value.

For reference, see:
https://developers.google.com/protocol-buffers/docs/reference/go-generated#enum

---

I'm not sure what the best way to test this is; the way the existing test cases work is fairly opaque to me. Any pointers (heh)?

### CODE REVIEW

**Comment by casualjim** [comment]
can you run `go generate ./generator` ?

**Comment by thetorpedodog** [comment]
Done.

**Review by casualjim — APPROVED** [review]

**Comment by thetorpedodog** [comment]
Is there anything else I need to do here?

**Comment by casualjim** [comment]
I fixed the build step on master, so if you update then the builds will hopefully pass

**Pull request merged**
