### PR TITLE
Enhance spec 

### PR DESCRIPTION
**Pull request by chenziliang**
Enhance spec to reflect swagger CLI usage for the yaml generation and avoid generating Go language extension

### CODE REVIEW

**Comment by chenziliang** [comment]
@casualjim did i need sign my commit again ?

**Comment by casualjim** [comment]
No but I have to wait for the build to finish

**Comment by casualjim** [comment]
O sorry I can only now see that it wants you to sign your commit. They always have to be signed :)

**Comment by chenziliang** [comment]
@casualjim done

**Pull request merged**
