### PR TITLE
Fix typo mulit vs multi

### LINKED ISSUE #518: Typo multipart/form-data as "Mulitpart"
## Problem statement
If you have a multipart/form-data consumer you get code generated with a typo *mulit* instead of *multi*.

## Steps to reproduce
Just generate any code that consumes a multipart/form-data.

Found this in the current repo:

```
go-swagger $ grep -r Mulit *
examples/task-tracker/restapi/configure_task_tracker.go:	api.MulitpartformConsumer = runtime.DiscardConsumer
examples/task-tracker/restapi/operations/task_tracker_api.go:	// MulitpartformConsumer registers a consumer for a "multipart/form-data" mime type
examples/task-tracker/restapi/operations/task_tracker_api.go:	MulitpartformConsumer runtime.Consumer
examples/task-tracker/restapi/operations/task_tracker_api.go:	if o.MulitpartformConsumer == nil {
examples/task-tracker/restapi/operations/task_tracker_api.go:		unregistered = append(unregistered, "MulitpartformConsumer")
examples/task-tracker/restapi/operations/task_tracker_api.go:			result["multipart/form-data"] = o.MulitpartformConsumer
generator/server_test.go:					assertInCode(t, "api.MulitpartformConsumer = runtime.DiscardConsumer", res)
```

### PR DESCRIPTION
**Pull request by fiorix**
Closes #518

### CODE REVIEW

**Comment by casualjim** [comment]
hi it fails this test: TestServer_MultipartForm

see log here: https://ci.vmware.run/go-swagger/go-swagger/628

**Comment by fiorix** [comment]
Yeah because it's comparing the good name to the old typo `api.Mulitpart...`. Didn't look back in the code but I'd guess it is missing more changes. Notice I had also fixed the same typo in go-openapi/errors so it's possible there's more in other packages.

**Comment by fiorix** [comment]
Should be good now.

**Comment by casualjim** [comment]
lgtm, thanks!

**Pull request merged**
